apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: SOME_ENV
      type: string
  steps:
    - name: print-build-number
      image: alpine
      script: |
        #!/bin/sh
        echo "SOME_ENV from pipeline param: $(params.SOME_ENV)"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: echo-pipeline
spec:
  params:
    - name: SOME_ENV
      type: string
  tasks:
    - name: echo
      taskRef:
        name: echo-task
      params:
        - name: SOME_ENV
          value: $(params.SOME_ENV)
