apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task
spec:
  inputs:
    params:
      - name: buildnumber
        description: test
      - name: SOME_ENV
  steps:
    - name: task-two-step-four
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(inputs.params.buildnumber)
        - name: SOME_ENV
          value: $(params.SOME_ENV)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "test"
          echo "BUILD_NUMBER: ${BUILD_NUMBER}"
          echo "SOME_ENV: ${SOME_ENV}"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: SOME_ENV
  tasks:
    - name: sample-out-task
      taskRef:
        name: sample-out-task
      params:
        - name: SOME_ENV
          value: $(params.SOME_ENV)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
    - name: SOME_ENV
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: SOME_ENV
          value: $(params.SOME_ENV)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
