apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task
spec:
  inputs:
    params:
      - name: buildnumber
        description: test       
  steps:
    - name: task-two-step-four
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(inputs.params.buildnumber)
      command: ['bash']
      args:
        - |
          echo "DEBUG | devsecops_pipeline_metrics={\"ibm_toolchain_pipeline_cd_change_request_check_deployment_readinees_seconds\": 54, \"ibm_toolchain_pipeline_cd_change_request_create_seconds\": 25, \"ibm_toolchain_pipeline_cd_change_request_check_approval_seconds\": 10, \"ibm_toolchain_pipeline_cd_change_request_implement_seconds\": 122}"
          echo "test"
          echo "DEBUG | devsecops_pipeline_metrics={\"ibm_toolchain_pipeline_cd_containerize_check_deployment_readinees_seconds\": 5, \"ibm_toolchain_pipeline_cd_containerize_create_seconds\": 15, \"ibm_toolchain_pipeline_cd_containerize_check_approval_seconds\": 45, \"ibm_toolchain_pipeline_cd_containerize_implement_seconds\": 12}"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
  tasks:
    - name: sample-out-task
      taskRef:
        name: sample-out-task
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
