apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: my-task
spec:
  params:
    - name: SOME_ENV
  steps:
    - name: my-step
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.83
      env:
        - name: SOME_ENV
          value: $(params.SOME_ENV)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "test"
          echo "SOME_ENV is: ${SOME_ENV}"
          echo "Cloning GH Repository"
          git clone --depth=1 https://github.ibm.com/otc-cti-broker
          echo "Cloning done"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: SOME_ENV
  tasks:
    - name: my-task
      taskRef:
        name: my-task
      params:
        - name: SOME_ENV
          value: $(params.SOME_ENV)
---
apiVersion: tekton.dev/v1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
    - name: SOME_ENV
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: SOME_ENV
          value: $(params.SOME_ENV)
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
